# Generated by Django 3.0.5 on 2022-10-07 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Available',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(null=True, verbose_name='Available_time')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ImageField(null=True, upload_to='uploads')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='Name')),
                ('age', models.IntegerField(null=True, verbose_name='Age')),
                ('mobile', models.CharField(max_length=15, null=True, verbose_name='Mobile')),
                ('address', models.CharField(blank=True, max_length=150, null=True, verbose_name='ADDRESS')),
                ('experience', models.IntegerField(null=True, verbose_name='Experience')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Name')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Age')),
                ('mobile', models.IntegerField(blank=True, null=True, verbose_name='Mobile')),
                ('address', models.CharField(blank=True, max_length=150, null=True, verbose_name='ADDRESS')),
                ('experience', models.CharField(max_length=20, null=True, verbose_name='Experience')),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True, verbose_name='Name')),
                ('mobile', models.CharField(max_length=50, null=True, verbose_name='Mobile')),
                ('Address', models.CharField(max_length=150, null=True, verbose_name='Address')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10, null=True, verbose_name='Name')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='DOB')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=20, null=True, verbose_name='Gender')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, verbose_name='Mobile')),
                ('aadhar', models.BigIntegerField(blank=True, null=True, verbose_name='AADHAR_NUMBER')),
                ('Ptype', models.CharField(blank=True, default='NewCustomer', max_length=100, null=True, verbose_name='PatientType')),
            ],
        ),
        migrations.CreateModel(
            name='Specialist_doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True, verbose_name='Name')),
                ('type', models.TextField(null=True, verbose_name='Type')),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_date', models.DateField(null=True, verbose_name='Treatment_date')),
                ('treatment_name', models.TextField(max_length=100, null=True, verbose_name='Treatment_name')),
                ('appointment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='master.Patient')),
                ('doctor_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='master.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Symptoms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True, verbose_name='Name')),
                ('role', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=20, null=True, verbose_name='Mobile')),
                ('doctor_fee', models.CharField(max_length=15, null=True, verbose_name='Doctor_fees')),
                ('start_date', models.DateField(null=True, verbose_name='start_Date')),
                ('end_date', models.DateField(null=True, verbose_name='End Date')),
                ('room_rent', models.CharField(max_length=15, null=True, verbose_name='Room Rent')),
                ('Total', models.CharField(max_length=8, null=True, verbose_name='Total=')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='master.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('med_type', models.CharField(max_length=60, null=True, verbose_name='medicine_type')),
                ('med_name', models.CharField(max_length=30, null=True, verbose_name='Medicine_Name')),
                ('limit', models.CharField(max_length=20, null=True, verbose_name='limit')),
                ('patient_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='master.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Discharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admit_reason', models.CharField(max_length=50, null=True, verbose_name='reason')),
                ('invoice', models.CharField(max_length=100, null=True, verbose_name='Invoice')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='master.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pat_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='master.Patient')),
                ('symptoms', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='master.Symptoms')),
                ('timing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='master.Available')),
            ],
        ),
    ]
