# Generated by Django 3.0.5 on 2022-10-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(default=0, max_length=254, verbose_name='Email'),
            preserve_default=False,
        ),
    ]
