# Generated by Django 3.0.5 on 2022-10-08 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_patient_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='password',
            field=models.CharField(blank=True, max_length=30, verbose_name='Password'),
        ),
    ]
