# Generated by Django 3.0.5 on 2022-10-10 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_remove_patient_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='uploads'),
        ),
    ]
