# Generated by Django 4.1 on 2022-10-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_auto_20221010_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='available',
            name='time',
            field=models.TimeField(default=0, verbose_name='Available_time'),
            preserve_default=False,
        ),
    ]
