# Generated by Django 4.1 on 2022-10-12 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_alter_available_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='available',
            name='time',
            field=models.TimeField(null=True, verbose_name='Available_time'),
        ),
    ]
